### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by liu1999888** [LightningSw/TeamInsightX#6]
云顶玩家，主要就是查看好友最近都在拿什么偷分，今天发现无法使用了，而且进入客户端和重登客户端时间变长，我最近并没有增加其他插件，不过还是可以正常进入客户端的，进入客户端后插件成功载入的窗口也会正常弹出，就是时间明显变长

**Comment by snowflake-x** [comment]
?我自己都不知道这插件还能用于云顶，不过你的问题应该是，网络环境有变化
